# Generated by cpp11: do not edit by hand

cpp_burn_sparse <- function(wkb_list, xmin, ymin, xmax, ymax, ncol, nrow) {
  .Call(`_denseburn_cpp_burn_sparse`, wkb_list, xmin, ymin, xmax, ymax, ncol, nrow)
}

cpp_denseburn_init <- function() {
  invisible(.Call(`_denseburn_cpp_denseburn_init`))
}

cpp_scanline_burn <- function(wkb_list, xmin, ymin, xmax, ymax, ncol, nrow) {
  .Call(`_denseburn_cpp_scanline_burn`, wkb_list, xmin, ymin, xmax, ymax, ncol, nrow)
}
